### ISSUE TITLE
Aggiungere verifica finale xsd/firma

### ISSUE THREAD

**Issue by umbros** [italia/spid-metadata-signer#2]
Aggiungere la verifica del metadata firmato sia con l'xsd che per la validità della firma

**Comment by cmezzetti** [comment]
Che genere di verifica avevi in mente? 
La verifica dello schema del saml metadata profile o qualcosa di più specifico SPID?
A memoria mi sembra che ci siano dei dettagli di SPID incompatibili con la standard SAML, non ricordo se a livello di metadata o di request
